sudo: false
language: node_js
node_js:
   - 8
cache:
  directories:
  - src/bower
notifications:
  slack: sap-pi-tools:$SLACK_TOKEN
before_script:
- bower install
after_script:
- grunt uglify && grunt mocha_istanbul && grunt coveralls
- if [[ $TRAVIS_PULL_REQUEST == 'false']]; then npm run snyk-monitor; fi
- if [[ $TRAVIS_PULL_REQUEST == 'false' && $TRAVIS_BRANCH == 'release-green' ]]; then ./.cf.sh cla-assistant-green; fi
- if [[ $TRAVIS_PULL_REQUEST == 'false' && $TRAVIS_BRANCH == 'master' ]]; then ./.cf.sh cla-assistant-staging; fi
- if [[ $TRAVIS_PULL_REQUEST == 'false' && $TRAVIS_BRANCH == 'release' ]]; then ./.cf.sh cla-assistant; fi
